# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f2952efccc3c6d9fa45716a87e59f6f7332a12a7ee37c95f285398a78ff66b734f237fe30704616dd3f5b41790f7855faf7a007d425f0601821c7b79263928d

test:
  secret_key_base: 35ff8a0c5d8bbfaa23e4ffed53b651ea9a0549a2c2fb9e6e1a53251e727a2f6cbddd6495bafedce9276e7af737a16aeaf57d1f382773c77d07521c761fa50611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
